create extension if not exists "pgcrypto";

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  name text,
  login_method text,
  role text not null default 'user' check (role in ('user', 'owner', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  price integer not null,
  location text not null,
  city text not null,
  state text not null,
  zip_code text,
  property_type text not null check (property_type in ('house', 'apartment', 'condo', 'townhouse', 'villa', 'land', 'room', 'studio', 'shared-room', 'pg/hostel', 'independent-floor')),
  listing_type text not null check (listing_type in ('sale', 'rent', 'co-living')),
  bedrooms integer not null,
  bathrooms integer not null,
  square_feet integer not null,
  images text not null default '[]',
  featured boolean not null default false,
  status text not null default 'available' check (status in ('available', 'pending', 'sold')),
  approval_status text not null default 'pending' check (approval_status in ('pending', 'approved', 'rejected')),
  fee_status text not null default 'open' check (fee_status in ('open', 'won', 'paid')),
  created_by uuid not null references public.users(id),
  owner_name text,
  owner_email text,
  owner_phone text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  name text not null,
  email text not null,
  phone text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.owner_messages (
  id bigint generated by default as identity primary key,
  property_id bigint not null references public.properties(id) on delete cascade,
  sender_role text not null check (sender_role in ('admin', 'owner')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.platform_settings (
  id integer primary key,
  team_name text not null default 'RealEstate Pro Match Team',
  tagline text not null default 'We qualify tenants before connecting them to owners.',
  contact_phone text not null default '+91 98765 43210',
  contact_email text not null default 'agent@realestatepro.com',
  updated_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'reviewed', 'closed')),
  created_at timestamptz not null default now()
);

alter table public.users
  add column if not exists role text not null default 'user';

alter table public.properties
  add column if not exists approval_status text not null default 'pending',
  add column if not exists fee_status text not null default 'open',
  add column if not exists owner_name text,
  add column if not exists owner_email text,
  add column if not exists owner_phone text;

alter table public.properties
  drop constraint if exists properties_property_type_check;

alter table public.properties
  add constraint properties_property_type_check
  check (property_type in ('house', 'apartment', 'condo', 'townhouse', 'villa', 'land', 'room', 'studio', 'shared-room', 'pg/hostel', 'independent-floor'));

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

drop trigger if exists properties_set_updated_at on public.properties;
create trigger properties_set_updated_at
before update on public.properties
for each row execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.properties enable row level security;
alter table public.inquiries enable row level security;
alter table public.owner_messages enable row level security;
alter table public.platform_settings enable row level security;
alter table public.contact_messages enable row level security;

drop policy if exists "public can read properties" on public.properties;
create policy "public can read properties"
on public.properties
for select
to public
using (true);

drop policy if exists "authenticated can create inquiries" on public.inquiries;
create policy "authenticated can create inquiries"
on public.inquiries
for insert
to authenticated
with check (true);

drop policy if exists "anon can create inquiries" on public.inquiries;
create policy "anon can create inquiries"
on public.inquiries
for insert
to anon
with check (true);

drop policy if exists "authenticated can create contact messages" on public.contact_messages;
create policy "authenticated can create contact messages"
on public.contact_messages
for insert
to authenticated
with check (true);

drop policy if exists "anon can create contact messages" on public.contact_messages;
create policy "anon can create contact messages"
on public.contact_messages
for insert
to anon
with check (true);

insert into storage.buckets (id, name, public)
values ('property-images', 'property-images', true)
on conflict (id) do nothing;

insert into public.platform_settings (id, team_name, tagline, contact_phone, contact_email)
values (1, 'RealEstate Pro Match Team', 'We qualify tenants before connecting them to owners.', '+91 98765 43210', 'agent@realestatepro.com')
on conflict (id) do nothing;
